authors/urls.py
from django.urls import path

from authors.views import AuthorRegisterView, login_create, login_view
from django.contrib.auth.views import (LogoutView)


app_name = "authors"

urlpatterns = [
    path("authors/login/", login_view, name="login"),
    path("authors/login/create/", login_create, name="login-create"),
    path("authors/register/", AuthorRegisterView.as_view(), name="register"),
    path("authors/logout/", LogoutView.as_view(), name="logout")
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("authors.urls")),
    path('', include("questions.urls")),
    path('admin/', admin.site.urls),
]

questions/urls.py
from django.urls import path

from . views import (AuthorQuestionListView, QuestionCreateView, QuestionDeleteView,
                     QuestionDetailView, QuestionListView, QuestionUpdateView)

app_name = "questions"

urlpatterns = [
    path("question/your-questions/", AuthorQuestionListView.as_view(),
         name="author-questions"),
    path("question/<int:pk>/detail/", QuestionDetailView.as_view(),
         name="detail"),
    path("question/<int:pk>/update/", QuestionUpdateView.as_view(),
         name="update"),
    path("question/<int:pk>/delete/", QuestionDeleteView.as_view(),
         name="delete"),
    path("question/create/", QuestionCreateView.as_view(), name="create"),
    path("", QuestionListView.as_view(), name="list"),
]

questions/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Question(models.Model):
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    question_text = models.CharField(max_length=150)
    pub_date = models.DateTimeField(default=timezone.now)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse("questions:detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    question = models.ForeignKey(
        Question, null=True, on_delete=models.SET_NULL, related_name="comment")
    comment_text = models.TextField("", max_length=500)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.comment_text[:20]

questions/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . models import Comment, Question


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text", ]
        widgets = {
            "comment_text": forms.Textarea(attrs={
                "placeholder": "Write your answer here..."
            })
        }

    def clean_comment_text(self):
        ct = self.cleaned_data["comment_text"]

        if len(ct) <= 3:
            raise ValidationError(
                "Your comment must have more than 3 characters.",
                code="invalid")

        return ct


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question_text", ]
        widgets = {
            "question_text": forms.Textarea(attrs={
                "placeholder": "Write your question here..."
            })
        }

    def clean_question_text(self):
        qt = self.cleaned_data["question_text"]

        if len(qt) <= 15:
            raise ValidationError(
                "Your question must have more than 15 characters.", code="invalid")

        return qt

questions/views.py
from django.views.generic import (
    CreateView, DetailView, ListView, UpdateView, DeleteView,
)
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin

from .models import Question
from . forms import CommentForm, QuestionForm

# Create your views here.


class QuestionListView(ListView):
    model = Question
    context_object_name = "question_list"
    template_name = "questions/question_list.html"
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        qs = Question.objects.filter(is_published=True)
        return qs


class QuestionDetailView(DetailView, FormMixin):
    model = Question
    context_object_name = "question"
    template_name = "questions/question_detail.html"
    form_class = CommentForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        form.instance.question = self.object
        form.instance.author = self.request.user
        new_comment.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("questions:detail", kwargs={"pk": self.object.pk})


class QuestionCreateView(CreateView):
    model = Question
    template_name = "questions/question_create.html"
    context_object_name = "comment"
    form_class = QuestionForm

    def form_valid(self, form):
        new_question = form.save(commit=False)
        form.instance.author = self.request.user
        new_question.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("questions:author-questions")


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = "questions/question_update.html"
    context_object_name = "question"
    form_class = QuestionForm

    def form_valid(self, form):
        new_question = form.save(commit=False)
        form.instance.author = self.request.user
        new_question.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("questions:author-questions")


class QuestionDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Question
    template_name = "questions/question_delete.html"
    context_object_name = "question"
    success_message = "Your question was successfully deleted!"

    def get_success_url(self):
        return reverse_lazy("questions:author-questions")


class AuthorQuestionListView(ListView):
    model = Question
    context_object_name = "question_list"
    template_name = "questions/author_question_list.html"
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        qs = Question.objects.filter(
            author=self.request.user.id, is_published=False)
        return qs

questions/templates/questions/author_question_list.html
{% extends 'questions/base.html' %}

{% block title %}<title>Qan'A - Your questions</title>{% endblock title %}

{% block content %}
<div class="container">
    {% for message in messages %}
        {% if message.tags %}
            <div class="message-success">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}


    {% if request.user.is_authenticated %}
    <h4 class="py-3">{{ request.user }} &middot; Questions</h4>
    <div class="text-muted center-help-message my-3">
        &middot; Questions in this page are not published yet! &middot;
    </div> 
    <div class="text-muted center-help-message my-3">
        &middot; It's only possible to <b>edit</b> or <b>delete</b> your questions BEFORE it's published by the administration &middot;
    </div> 
    <div class="container">
        {% if question_list %}
            {% for question in question_list %}
            <div class="my-2">
                <div class="question-border"> 
                    <h2>{{ question.question_text }}</h2>
                    <p>{{ question.pub_date|date:"d/M/Y - H:i" }}</p>
                    <p>-- <a href="{% url 'questions:update' question.pk %}">Edit</a> | <a href="{% url 'questions:delete' question.pk %}">Delete</a> --</p>
                </div>
            </div>
            {% endfor %}
            {% include "questions/pagination.html" %}
        {% else %}
            <div class="question-border">
                <h4>No questions to show</h4>
            </div>
            {% endif %}
    </div>
    {% else %}
        <div class="container">
            <h4><a href="{% url 'authors:login' %}">You need to login first to see your questions.</a></h4>
            <h4><a href="{% url 'authors:register' %}">Or register if you don't have an account.</a></h4>
        </div>
    {% endif %}


</div>

{% endblock content %}

questions/templates/questions/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title></title>{% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'questions/css/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@600&display=swap" rel="stylesheet">  
  
  <div class="main-logo main-header-container">
    <a href="{% url 'questions:list' %}"><h1>Questions an'Answers</h1></a>
  </div>
    
  <div class="py-3">
    <ul class="nav justify-content-center nav-pills">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'questions:list' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'questions:create' %}">Make a Question</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'questions:author-questions' %}">Your questions</a>
      </li>
      <li class="nav-item">
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'authors:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link active" href="{% url 'authors:login' %}">Login</a>
      </li>
      <div class="m-2">or</div>
      <li>
        <a class="nav-link active" href="{% url 'authors:register' %}">Register</a>
      </li>
      {% endif %}
    </ul>

  </div>

  </head>
  <body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>

  <footer class="main-footer">
    <div class="developer">
      <a href="https://www.github.com/tsuk1N" target="_blank" rel="noreferrer noopener">Luan Silva | tsuk1N</a>
    </div>

    <div class="powered">
      <a href="https://www.djangoproject.com" target="_blank" rel="noreferrer noopener">Powered by Django Project</a>
    </div>
  </footer>
</html>

questions/templates/questions/pagination.html
{% if is_paginated %}
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a class="page-link page-number" href="?page=1">&laquo; First</a>
            {% comment %} <a class="page-link page-number" href="?page={{ page_obj.previous_page_number }}">Previous</a> {% endcomment %}
        {% endif %}

        {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page %}
                <a class="page-link page-number page-current" href="?page={{ page }}">{{ page }}</a>
            {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                <a class="page-link page-number" href="?page={{ page }}">{{ page }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            {% comment %} <a class="page-link page-number" href="?page={{ page_obj.next_page_number }}">Next</a> {% endcomment %}
            <a class="page-link page-number" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </div>
{% endif %}

questions/templates/questions/question_create.html
{% extends 'questions/base.html' %}

{% block title %}<title>Qan'A - Make your Question</title>{% endblock title %}

{% block content %}

<div class="container">
    {% if request.user.is_authenticated %}
        <div class="py-1">
            <div class="question-border">
                <h4>Make your Question</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="comment-form">
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="errorlist">{{ field.errors }}</div>
                            {% endif %}
                            {{ field }}
                        {% endfor %}    
                    </div>
                    <button type="submit" class="btn btn-primary my-2">Submit question</button>
                </form>
            </div>
        </div>
    {% else %}
        <h4><a href="{% url 'authors:login' %}">You need to login first to make your question.</a></h4>
        <h4><a href="{% url 'authors:register' %}">Or register if you don't have an account.</a></h4>
    {% endif %}
</div>

{% endblock content %}

questions/templates/questions/question_delete.html
{% extends 'questions/base.html' %}

{% block title %}<title>Qan'A - Index</title>{% endblock title %}

{% block content %}

<div class="container">
    {% if question.is_published == False %}
        {% if request.user == question.author %}
        <div class="py-1">
            <div class="question-border">
                <h4>Delete your Question</h4>
                <div class="center-error-message my-3">
                    <b> &middot; Are you sure you want to DELETE this question ? &middot; </b>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="">
                        {{ question }}    
                    </div>
                    <button type="submit" class="btn btn-primary my-4">Delete question</button>
                </form>
            </div>
        </div>
        {% endif %}
    {% else %}
        <h4>Question not found</h4>
    {% endif %}
</div>

{% endblock content %}

questions/templates/questions/question_detail.html
{% extends 'questions/base.html' %}

{% block title %}
    {% if question.is_published == False %}
        <title>Question not found</title>
    {% else %}
        <title>Qan'A - {{ question }}</title>
    {% endif %}
{% endblock title %}

{% block content %}
<div class="container">
    {% if question.is_published == False %}
        <h4>Question not found</h4>
    {% else %}
    <div class="py-1">
        <div class="question-border">
            <div class="question-inside-border">
            {% if question.author == None %}
                <div class="deleted-user">Deleted User</div>
            {% else %}
                <p>{{ question.author }}</p> 
            {% endif %}
                <h2>{{ question }}</h2>
                <div class="date-inside-border">
                    <p>{{ question.pub_date|date:"d/M/Y - H:i"  }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="question-border">
        <h4>Answers</h4>
        {% if request.user.is_authenticated %}
            {% if question.is_published == False %}
                <h4>It's not possible to answer a question not published.</h4>
            {% else %}
            <form action="" method="post">
                {% csrf_token %}
                <div class="comment-form">
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="errorlist">{{ field.errors }}</div>
                        {% endif %}
                        {{ field }}
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary my-2">Submit answer</button>
            </form>
            {% endif %}
        {% else %}
            <h4><a href="{% url 'authors:login' %}">You must login to write an answer.</a></h4>
        {% endif %}
        <div class="question-inside-border">
                {% if question.comment.all %}
                    {% for comment in question.comment.all %}
                        <div class="question-inside-border">
                            <div class="author-text-color">
                            {% if comment.author == None %}
                                <div class="deleted-user">Deleted User</div> &middot;
                            {% else %}
                                {{ comment.author }} &middot; 
                            {% endif %}
                                
                                <div class="text-muted author-text-color">
                                    {{ comment.pub_date|date:"d/M/Y - H:i" }}    
                                </div>
                            </div>
                            <h6>{{ comment.comment_text }}</h6>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Be the first one to write an answer!</p>
                {% endif %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

questions/templates/questions/question_list.html
{% extends 'questions/base.html' %}

{% block title %}<title>Qan'A - Index</title>{% endblock title %}

{% block content %}

<div class="container">
    {% for message in messages %}
        {% if message.tags %}
            <div class="message-success">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    
    {% if request.user.is_authenticated %}
        <h4>Welcome, {{ request.user }}</h4>
    {% endif %}

    {% if question_list %}
        {% for question in question_list %}
        <div class="py-1">
            <div class="question-border">
                {% if question.author == None %}
                    <div class="deleted-user">Deleted User</div>
                {% else %}
                    <p>{{ question.author }}</p> 
                {% endif %}
                <a href="{% url 'questions:detail' question.pk %}"><h2>{{ question.question_text }}</h2></a>
                <p>{{ question.pub_date|date:"d/M/Y - H:i" }}</p>
            </div>
        </div>
        {% endfor %}
        {% include "questions/pagination.html" %}
    {% else %}
        <div class="question-border">
            <h4>No questions to show</h4>
        </div>
    {% endif %}


</div>

{% endblock content %}

questions/templates/questions/question_update.html
{% extends 'questions/base.html' %}

{% block title %}<title>Qan'A - Index</title>{% endblock title %}

{% block content %}

<div class="container">
    {% if question.is_published == False %}
        {% if request.user == question.author %}
        <div class="py-1">
            <div class="question-border">
                <h4>Edit your Question</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="comment-form">
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="errorlist">{{ field.errors }}</div>
                            {% endif %}
                            {{ field }}
                        {% endfor %}    
                    </div>
                    <button type="submit" class="btn btn-primary my-2">Submit question</button>
                    <div class="text-muted">
                        &middot; It's only possible to <b>edit</b> your questions BEFORE it's published by the administration &middot;
                    </div>
                </form>
            </div>
        </div>
        {% endif %}
    {% else %}
        <h4>Question not found</h4>
    {% endif %}
</div>

{% endblock content %}